<a href="https://colab.research.google.com/github/2303A52083/23CSBTB39-40/blob/main/AIML_A1_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1 – Implement Basic Data Structures using Numpy, Pandas


In [12]:
import numpy as np
# 1.Lists
list1 = [1, 2, 3,'humera', 4, 5]
list2 = [6, 7, 8,'nuzhat', 9, 10]
print(list1[:])
print(list2[:])
# Type
print("Type of list1:", type(list1))
print("Type of list2:", type(list2))

# 2.Arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
print(array1[:])
print(array2[:])
# Type
print("Type of array1:", type(array1))
print("Type of array2:", type(array2))

# 3.Mathematical operations
multiplication = array1 * array2
division = array1 / array2
poweroff = array1 ** 2
print("Multiplication of array1 and array2:", multiplication)
print("Division of array1 by array2:", division)
print("Power of array1:", poweroff)

# 4.Combining text with numpy function to get textual output
add_text = f"Addition of Two:\n{array1} + {array2} = {array1 + array2}"
print(add_text)

# 5.implement np.sin(), log(), log2(), np.exp())
sin_values = np.sin(array1)
log_values = np.log(array1 + 1)  # Adding 1 to avoid log(0)
log2_values = np.log2(array1 + 1)  # Adding 1 to avoid log2(0)
exp_values = np.exp(array1)
print("Sine values of array1:", sin_values)
print("Log values of array1:", log_values)
print("Log2 values of array1:", log2_values)
print("Exponential values of array1:", exp_values)

# for array 2
sin_values2 = np.sin(array1)
log_values2 = np.log(array2+ 1)  # Adding 1 to avoid log(0)
log2_values2 = np.log2(array2 + 1)  # Adding 1 to avoid log2(0)
exp_values2 = np.exp(array2)
print("Sine values of array2:", sin_values2)
print("Log values of array2:", log_values2)
print("Log2 values of array2:", log2_values2)
print("Exponential values of array2:", exp_values2)

# Operations Using Pandas
import pandas as pd
list1 = [1, 2, 3, 4, 5]                       # Lists to be converted into DataFrames
list2 = [6, 7, 8, 9, 10]
df1 = pd.DataFrame(list1, columns=['Numbers']) # Creating DataFrames from lists
df2 = pd.DataFrame(list2, columns=['Numbers'])
df2.index = df1.index                         # Ensure both DataFrames have the same index
df_addition = df1.add(df2, fill_value=0)      # Performing operations using Pandas
df_multiplication = df1.multiply(df2, fill_value=1)
print("Addition DataFrame:\n", df_addition)
print("Multiplication DataFrame:\n", df_multiplication)










[1, 2, 3, 'humera', 4, 5]
[6, 7, 8, 'nuzhat', 9, 10]
Type of list1: <class 'list'>
Type of list2: <class 'list'>
[1 2 3 4 5]
[ 6  7  8  9 10]
Type of array1: <class 'numpy.ndarray'>
Type of array2: <class 'numpy.ndarray'>
Multiplication of array1 and array2: [ 6 14 24 36 50]
Division of array1 by array2: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power of array1: [ 1  4  9 16 25]
Addition of Two:
[1 2 3 4 5] + [ 6  7  8  9 10] = [ 7  9 11 13 15]
Sine values of array1: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log values of array1: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Log2 values of array1: [1.         1.5849625  2.         2.32192809 2.5849625 ]
Exponential values of array1: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine values of array2: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log values of array2: [1.94591015 2.07944154 2.19722458 2.30258509 2.39789527]
Log2 values of array2: [2.80735